spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=Prapti@1205
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

